#!/usr/bin/env php
<?php
// console

define('ROOT', __DIR__.'/');

require 'vendor/autoload.php';

$container = new League\Container\Container;

/**
 * Step 1: Add service providers
 */
$container->addServiceProvider('AppBundle\ServiceProvider\Config');
$container->addServiceProvider('AppBundle\ServiceProvider\Logger');
$container->addServiceProvider('AppBundle\ServiceProvider\Doctrine');

/**
 * Step 2: Instantiate the container
 */
Obullo\ServerRequestFactory::setContainer($container);
$container->share('request', Obullo\ServerRequestFactory::fromGlobals());

/**
 * Create your console commands
 */
use Symfony\Component\Console\Application;
use AppBundle\Command\LogHttpCommand;
use AppBundle\Command\GenerateBundleCommand;

$application = new Application();
$application->add(new LogHttpCommand($container));
$application->add(new GenerateBundleCommand($container));
$application->run();