<?php

namespace Obullo\Container\ServiceProvider;

use League\Container\ServiceProvider\BootableServiceProviderInterface as LeagueBootableServiceProviderInterface;

interface BootableServiceProviderInterface extends LeagueBootableServiceProviderInterface {}
